General_Preferred_Networks = [
    {"crypto": "Bitcoin", "id": "BTC", "preferred_network": "Bitcoin Network", "network_id": "BTC"},
    {"crypto": "Ethereum", "id": "ETH", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Binance Coin", "id": "BNB", "preferred_network": "Binance Smart Chain", "network_id": "BSC"},
    {"crypto": "Ripple", "id": "XRP", "preferred_network": "Ripple Network", "network_id": "XRP"},
    {"crypto": "Cardano", "id": "ADA", "preferred_network": "Cardano Network", "network_id": "ADA"},
    {"crypto": "Polkadot", "id": "DOT", "preferred_network": "Polkadot Network", "network_id": "DOT"},
    {"crypto": "Litecoin", "id": "LTC", "preferred_network": "Litecoin Network", "network_id": "LTC"},
    {"crypto": "Chainlink", "id": "LINK", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Stellar", "id": "XLM", "preferred_network": "Stellar Network", "network_id": "XLM"},
    {"crypto": "Tether", "id": "USDT", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "USD Coin", "id": "USDC", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Dogecoin", "id": "DOGE", "preferred_network": "Dogecoin Network", "network_id": "DOGE"},
    {"crypto": "Uniswap", "id": "UNI", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Bitcoin Cash", "id": "BCH", "preferred_network": "Bitcoin Cash Network", "network_id": "BCH"},
    {"crypto": "VeChain", "id": "VET", "preferred_network": "VeChain Thor Network", "network_id": "VET"},
    {"crypto": "Tron", "id": "TRX", "preferred_network": "Tron Network", "network_id": "TRX"},
    {"crypto": "Monero", "id": "XMR", "preferred_network": "Monero Network", "network_id": "XMR"},
    {"crypto": "EOS", "id": "EOS", "preferred_network": "EOS Network", "network_id": "EOS"},
    {"crypto": "Tezos", "id": "XTZ", "preferred_network": "Tezos Network", "network_id": "XTZ"},
    {"crypto": "Cosmos", "id": "ATOM", "preferred_network": "Cosmos Network", "network_id": "ATOM"},
    {"crypto": "Solana", "id": "SOL", "preferred_network": "Solana Network", "network_id": "SOL"},
    {"crypto": "Aave", "id": "AAVE", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Algorand", "id": "ALGO", "preferred_network": "Algorand Network", "network_id": "ALGO"},
    {"crypto": "Filecoin", "id": "FIL", "preferred_network": "Filecoin Network", "network_id": "FIL"},
    {"crypto": "IOTA", "id": "MIOTA", "preferred_network": "IOTA Network", "network_id": "IOTA"},
    {"crypto": "NEO", "id": "NEO", "preferred_network": "NEO Network", "network_id": "NEO"},
    {"crypto": "Dash", "id": "DASH", "preferred_network": "Dash Network", "network_id": "DASH"},
    {"crypto": "Zcash", "id": "ZEC", "preferred_network": "Zcash Network", "network_id": "ZEC"},
    {"crypto": "Compound", "id": "COMP", "preferred_network": "Ethereum Network", "network_id": "ETH"},
    {"crypto": "Maker", "id": "MKR", "preferred_network": "Ethereum Network", "network_id": "ETH"}
]